version: '3.8'
services:
  vscode:
    build: 
      context: .
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PYTHON_VERSION=${PYTHON_VERSION}
      - USERNAME=${USERNAME}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_EMAIL=${GIT_EMAIL}
    platform: linux/amd64
    image: vscode-webui
    ports:
      - "8080:8080"
      - "2222:22"
    volumes:
      - D:/dev/Users/${USERNAME}/Documents/projects/containers/vscode/projects:/home/${USERNAME}/projects